#!/bin/bash
player=$(echo ${1} | tr '[:upper:]' '[:lower:]')
timeout=${2}
ip=${3}
if [[ ${player} == "white" ]]
then
	echo WHITE
	java -jar neurowhite.jar  ${timeout}  ${ip}
fi
if [[ ${player} == "black" ]]
then
	echo BLACK
	java -jar neuroblack.jar  ${timeout}  ${ip}
fi
